<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'VendorPrefix\\Webuni\\FrontMatter\\' => array($vendorDir . '/webuni/front-matter/src'),
    'VendorPrefix\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'VendorPrefix\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'VendorPrefix\\Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'VendorPrefix\\Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'VendorPrefix\\League\\Config\\' => array($vendorDir . '/league/config/src'),
    'VendorPrefix\\League\\CommonMark\\' => array($vendorDir . '/league/commonmark/src'),
    'VendorPrefix\\Dflydev\\DotAccessData\\' => array($vendorDir . '/dflydev/dot-access-data/src'),
);
